from config import (
    INITIAL_TOP_K,
    FOLLOW_UP_TOP_K,
    RELEVANCE_DISTANCE_THRESHOLD,
    MMR_FETCH_K,
    MMR_LAMBDA,
)


def deduplicate_results(results):
    """
    Remove duplicate chunks using document ID + chunk ID.
    """

    unique_results = {}

    for result in results:
        key = (
            result.metadata.get("document_id"),
            result.metadata.get("chunk_id"),
        )

        unique_results[key] = result

    return list(unique_results.values())


def filter_relevant_results(results_with_scores):
    """
    Filter retrieved chunks using the FAISS distance threshold.

    In our current setup:
        smaller distance = closer semantic match
        larger distance = weaker semantic match

    The threshold is empirical and specific to our current:
        - embedding model
        - corpus
        - chunking strategy
        - FAISS index
    """

    relevant_results = []

    for document, score in results_with_scores:

        if score <= RELEVANCE_DISTANCE_THRESHOLD:
            relevant_results.append(
                (document, score)
            )

        else:
            print(
                f"Rejected chunk: distance {score:.4f} "
                f"> threshold "
                f"{RELEVANCE_DISTANCE_THRESHOLD:.2f}"
            )

    return relevant_results


def initial_search(vector_store, query):
    """
    Perform initial retrieval.

    Step 1:
        Run ordinary FAISS similarity search with scores.
        We use this for the relevance gate.

    Step 2:
        If no chunks survive the threshold, return [].

    Step 3:
        If the query appears relevant to the corpus,
        run MMR retrieval to select a more diverse
        final set of chunks.
    """

    # ---------------------------------------------------------
    # Step 1: Raw FAISS score search
    # ---------------------------------------------------------

    results_with_scores = (
        vector_store.similarity_search_with_score(
            query,
            k=INITIAL_TOP_K,
        )
    )

    print_retrieval_debug(
        query,
        results_with_scores,
        title="INITIAL SEARCH RESULTS",
    )

    # ---------------------------------------------------------
    # Step 2: Relevance gate
    # ---------------------------------------------------------

    filtered_results = filter_relevant_results(
        results_with_scores
    )

    print(
        f"\nRelevant chunks surviving threshold: "
        f"{len(filtered_results)} / "
        f"{len(results_with_scores)}"
    )

    if not filtered_results:
        return []

    # ---------------------------------------------------------
    # Step 3: MMR retrieval
    # ---------------------------------------------------------
    #
    # We now know the query is relevant enough to the corpus.
    #
    # MMR retrieves a larger candidate pool and selects
    # a diverse final set.
    # ---------------------------------------------------------

    mmr_results = (
        vector_store.max_marginal_relevance_search(
            query,
            k=INITIAL_TOP_K,
            fetch_k=MMR_FETCH_K,
            lambda_mult=MMR_LAMBDA,
        )
    )

    print_document_debug(
        query,
        mmr_results,
        title="MMR SELECTED RESULTS",
    )

    return deduplicate_results(
        mmr_results
    )


def run_follow_up_searches(
    vector_store,
    existing_results,
    search_queries,
):
    """
    Execute follow-up searches generated by the planner.

    For now:
        - follow-up searches still use normal similarity search
        - MMR is used only for the initial search

    This keeps the experiment controlled and avoids changing
    too many parts of the pipeline at once.
    """

    previous_count = len(existing_results)

    combined_results = list(
        existing_results
    )

    for search_query in search_queries:

        results_with_scores = (
            vector_store.similarity_search_with_score(
                search_query,
                k=FOLLOW_UP_TOP_K,
            )
        )

        print_retrieval_debug(
            search_query,
            results_with_scores,
            title="FOLLOW-UP SEARCH RESULTS",
        )

        new_documents = [
            document
            for document, score
            in results_with_scores
        ]

        combined_results.extend(
            new_documents
        )

    combined_results = (
        deduplicate_results(
            combined_results
        )
    )

    added_count = (
        len(combined_results)
        - previous_count
    )

    return combined_results, added_count


def print_retrieval_debug(
    query,
    results_with_scores,
    title,
):
    """
    Display FAISS retrieval results with distances.

    Lower score = closer semantic match.
    Higher score = weaker semantic match.

    These are not percentages or probabilities.
    """

    print("\n------------------------------------------")
    print(title)
    print("------------------------------------------")

    print(f"Query: {query}\n")

    for rank, (
        document,
        score,
    ) in enumerate(
        results_with_scores,
        start=1,
    ):

        page = document.metadata.get(
            "page"
        )

        preview = (
            document.page_content
            .replace("\n", " ")
            .strip()
        )

        preview = preview[:300]

        print(
            f"Result #{rank}"
        )

        print(
            f"FAISS distance: {score:.4f}"
        )

        print(
            f"Page: {page}"
        )

        print(
            f"Preview: {preview}"
        )

        print()


def print_document_debug(
    query,
    documents,
    title,
):
    """
    Display document-only retrieval results.

    MMR does not return the same simple distance output as
    similarity_search_with_score(), so this prints the selected
    chunks without pretending they have FAISS distance scores.
    """

    print("\n------------------------------------------")
    print(title)
    print("------------------------------------------")

    print(f"Query: {query}\n")

    for rank, document in enumerate(
        documents,
        start=1,
    ):

        page = document.metadata.get(
            "page"
        )

        preview = (
            document.page_content
            .replace("\n", " ")
            .strip()
        )

        preview = preview[:300]

        print(
            f"Result #{rank}"
        )

        print(
            f"Page: {page}"
        )

        print(
            f"Preview: {preview}"
        )

        print()